from django.db import models

# Create your models here.

class Matches(models.Model):
    season=models.IntegerField()
    city=models.CharField(null=True,max_length=100)
    date=models.DateField(null=True)
    team1=models.CharField(max_length=100)
    team2=models.CharField(max_length=100)
    toss_winner=models.CharField(max_length=100)
    toss_decision=models.CharField(max_length=100)
    result=models.CharField(max_length=100)
    dl_applied=models.BooleanField(default=False)
    winner=models.CharField(null=True,max_length=100)
    win_by_runs=models.IntegerField()
    win_by_wickets = models.IntegerField()
    player_of_match=models.CharField(null=True,max_length=100)
    venue=models.CharField(null=True,max_length=100)
    umpire1=models.CharField(null=True,max_length=100)
    umpire2=models.CharField(null=True,max_length=100)
    umpire3=models.CharField(null=True,max_length=100)


class Match(models.Model):
    match_id=models.IntegerField(default=-1)
    season=models.IntegerField()
    city=models.CharField(null=True,max_length=100)
    date=models.DateField(null=True)
    team1=models.CharField(max_length=100)
    team2=models.CharField(max_length=100)
    toss_winner=models.CharField(max_length=100)
    toss_decision=models.CharField(max_length=100)
    result=models.CharField(max_length=100)
    dl_applied=models.BooleanField(default=False)
    winner=models.CharField(null=True,max_length=100)
    win_by_runs=models.IntegerField()
    win_by_wickets = models.IntegerField()
    player_of_match=models.CharField(null=True,max_length=100)
    venue=models.CharField(null=True,max_length=100)
    umpire1=models.CharField(null=True,max_length=100)
    umpire2=models.CharField(null=True,max_length=100)
    umpire3=models.CharField(null=True,max_length=100)

class Deliveries(models.Model):
    inning=models.IntegerField()
    batting_team=models.CharField(max_length=100)
    bowling_team=models.CharField(max_length=100)
    over=models.IntegerField()
    ball=models.IntegerField()
    batsman=models.CharField(max_length=100)
    non_striker = models.CharField(max_length=100)
    bowler = models.CharField(max_length=100)
    is_super_over=models.BooleanField(default=False)
    wide_runs=models.IntegerField()
    bye_runs = models.IntegerField()
    legbye_runs = models.IntegerField()
    noball_runs=models.IntegerField()
    penalty_runs = models.IntegerField()
    batsman_runs = models.IntegerField()
    extra_runs = models.IntegerField()
    total_runs=models.IntegerField()
    player_dismissed=models.CharField(null=True,max_length=100)
    dismissal_kind=models.CharField(null=True,max_length=100)
    fielder=models.CharField(null=True,max_length=100)
    match=models.ForeignKey(Match,on_delete=models.CASCADE)
