# Generated by Django 2.1.2 on 2019-06-17 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('batting_team', models.CharField(max_length=30)),
                ('bowling_team', models.CharField(max_length=30)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsmen', models.CharField(max_length=30)),
                ('non_striker', models.CharField(max_length=30)),
                ('bowler', models.CharField(max_length=30)),
                ('is_super_over', models.BooleanField(default=False)),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsmen_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(max_length=30, null=True)),
                ('dissimal_kind', models.CharField(max_length=30, null=True)),
                ('fielder', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('date', models.DateField(null=True)),
                ('team1', models.CharField(max_length=30)),
                ('team2', models.CharField(max_length=30)),
                ('toss_winner', models.CharField(max_length=30)),
                ('toss_decision', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=20)),
                ('dl_applied', models.BooleanField(default=False)),
                ('winner', models.CharField(max_length=20)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=20)),
                ('umpire1', models.CharField(max_length=20)),
                ('umpire2', models.CharField(max_length=20)),
                ('umpire3', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deliveries',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Matches'),
        ),
    ]
