# Generated by Django 2.1.2 on 2019-06-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='venue',
            field=models.CharField(max_length=40),
        ),
    ]
