# Generated by Django 2.1.2 on 2019-06-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_auto_20190617_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='batsmen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='batting_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='bowler',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='bowling_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='dissimal_kind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='fielder',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='non_striker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='player_dismissed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player_of_match',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matches',
            name='result',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matches',
            name='team2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matches',
            name='toss_decision',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matches',
            name='toss_winner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.CharField(max_length=100),
        ),
    ]
