# Generated by Django 2.1.2 on 2019-06-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20190617_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='umpire1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
