# Generated by Django 2.1.2 on 2019-06-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20190617_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='player_of_match',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='winner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
