# Generated by Django 2.1.2 on 2019-06-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20190617_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
