# Generated by Django 2.1.2 on 2019-06-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_auto_20190617_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('toss_winner', models.CharField(max_length=100)),
                ('toss_decision', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('dl_applied', models.BooleanField(default=False)),
                ('winner', models.CharField(max_length=100, null=True)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(max_length=100, null=True)),
                ('venue', models.CharField(max_length=100, null=True)),
                ('umpire1', models.CharField(max_length=100, null=True)),
                ('umpire2', models.CharField(max_length=100, null=True)),
                ('umpire3', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.Match'),
        ),
    ]
