# Generated by Django 2.1.2 on 2019-06-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_auto_20190617_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='batsmen',
            new_name='batsman',
        ),
    ]
