# Generated by Django 2.1.2 on 2019-06-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_auto_20190617_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(default=-1),
        ),
    ]
