# Generated by Django 2.1.2 on 2019-06-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_auto_20190617_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='batsmen_runs',
            new_name='batsman_runs',
        ),
    ]
