# Generated by Django 2.1.2 on 2019-06-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_auto_20190617_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='dissimal_kind',
            new_name='dismissal_kind',
        ),
    ]
